name: Android CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decrypt secret key file
        shell: bash
        run: |
          ./.github/scripts/decrypt_key.sh
          echo "KEY_STORE=$(cat ./keystore.jks | base64 | tr -d '\n')" >> $GITHUB_ENV
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - name: test if key is present
        run: find . -name "keystore.jks"
      - name: Test with Gradle
        run: ./gradlew test
      - name: Assemble Release
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK with keystore
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: $KEY_STORE
          alias: ${{ secrets.ALIAS_NAME }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.ALIAS_PASS }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ steps.sign_app.outputs.signedReleaseFile }}
          asset_name: sun-${{ github.ref_name }}.apk
          overwrite: true
          prerelease: true
          draft: true
          body: "Release ${{ github.ref_name }}"
